apiVersion: batch/v1
kind: Job
metadata:
  name: countdown4c
  namespace: mobile
spec:
  template:
    metadata:
      name: countdown4
    spec:
      containers:
      - name: counter
        image: centos:7
        command:
         - "bin/bash"
         - "-c"
         - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never
